// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type FilterRequest struct {
	Message string `json:"message"`
	UserId  string `json:"user_id"`
}

type FilterResponse struct {
	Original    string   `json:"original"`
	Filtered    string   `json:"filtered"`
	DangerLevel string   `json:"danger_level"`
	Triggers    []string `json:"triggers"`
	Note        string   `json:"note"`
}
